apiVersion: apps/v1
kind: Deployment
metadata:
  name: binarycalculatorDeployment
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: binarycalculator
  template:
    metadata:
      labels:
        app: binarycalculator
    spec:
      containers:
      - name: binarycalculator
        image: us-central1-docker.pkg.dev/sq-lab-489102/sofe3980u/binarycalculator:latest
        ports:
        - containerPort: 8080
